# Generated by Django 4.1.7 on 2023-06-17 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Eshop", "0002_order_orderproduct"),
    ]

    operations = [
        migrations.RemoveField(model_name="shoppingcart", name="client",),
        migrations.AddField(
            model_name="client",
            name="shopping_cart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Eshop.shoppingcart",
            ),
        ),
    ]
