# Generated by Django 4.1.7 on 2023-06-17 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Eshop", "0003_remove_shoppingcart_client_client_shopping_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="shopping_cart",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Eshop.shoppingcart",
            ),
        ),
    ]
