# Generated by Django 4.1.7 on 2023-06-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Eshop", "0004_alter_client_shopping_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
