# Generated by Django 4.1.7 on 2023-06-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Eshop", "0005_product_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_category",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
